[package]
name = "server_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.9"
gethostname = "1.1.0"
image = "0.25.10"
lazy_static = "1.5.0"
midir = "0.11.0"
rand = "0.10.1"
reqwest = { version = "0.13.4", features = ["json"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
socketioxide = "0.18.3"
tokio = { version = "1.52.3", features = ["full"] }
tower-http = { version = "0.6.11", features = ["fs"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
tray-icon = "0.24.0"
windows-sys = { version = "0.61.2", features = ["Win32_UI_WindowsAndMessaging", "Win32_Foundation"] }
midi_common = { path = "../midi_common" }
tokio-util = "0.7"
unicode-normalization = "0.1"
cpal = "0.15.3"
rustfft = "6.2.0"
opus-rs = "0.1"
